'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SirusPatientMaster
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SirusPatientMaster.InterfacePatientMaster")>  _
    Public Interface InterfacePatientMaster
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfacePatientMaster/PatientInsert", ReplyAction:="http://tempuri.org/InterfacePatientMaster/PatientInsertResponse")>  _
        Function PatientInsert( _
                    ByVal PatName As String,  _
                    ByVal AliasName As String,  _
                    ByVal Gender As Char,  _
                    ByVal IDType As String,  _
                    ByVal IDCode As String,  _
                    ByVal Addr1 As String,  _
                    ByVal Addr2 As String,  _
                    ByVal City As String,  _
                    ByVal State As String,  _
                    ByVal byvalZipCode As String,  _
                    ByVal Phone As String,  _
                    ByVal Mobile As String,  _
                    ByVal Fax As String,  _
                    ByVal DOB As Date,  _
                    ByVal Nationality As String,  _
                    ByVal Religion As String,  _
                    ByVal ethnicity As String,  _
                    ByVal BirthCountry As String,  _
                    ByVal Place As String,  _
                    ByVal BirthCertificate As String,  _
                    ByVal YearsofRes As Integer,  _
                    ByVal MarStatus As String,  _
                    ByVal Spouse As String,  _
                    ByVal Child As Integer,  _
                    ByVal TotChild As Integer,  _
                    ByVal Occupation As String,  _
                    ByVal Employed As String,  _
                    ByVal RegDate As Date,  _
                    ByVal Visits As Integer,  _
                    ByVal GuarantorMRNo As String,  _
                    ByVal GuarantorName As String,  _
                    ByVal GuarantorIDCode As String,  _
                    ByVal GuarantorGender As Char,  _
                    ByVal GuarantorAddress As String,  _
                    ByVal GuarantorCity As String,  _
                    ByVal GuarantorPhone As String,  _
                    ByVal GuarantorOfficeName As String,  _
                    ByVal GuarantorOffAddress As String,  _
                    ByVal GuarantorMobile As String,  _
                    ByVal GuarantorEmpCode As String,  _
                    ByVal GuarantorEmpPosition As String,  _
                    ByVal GuarantorDepartment As String,  _
                    ByVal GuarantorRelation As String,  _
                    ByVal GuarantorOffTel As String,  _
                    ByVal IntPtr As String,  _
                    ByVal Language As String,  _
                    ByVal DoctCode As String,  _
                    ByVal CorpClient As String,  _
                    ByVal FinClass As String,  _
                    ByVal DebitorCode As String,  _
                    ByVal DebitorRefCode As String,  _
                    ByVal CreditCardNo As String,  _
                    ByVal CreditCardExp As Date,  _
                    ByVal ContactMRNo As String,  _
                    ByVal ConTactName As String,  _
                    ByVal ContactIDCode As String,  _
                    ByVal ContactGender As String,  _
                    ByVal ContactAddress As String,  _
                    ByVal ContactCity As String,  _
                    ByVal ContactPhone As String,  _
                    ByVal ContactRelation As String,  _
                    ByVal ContactLang As String,  _
                    ByVal FatherMRNo As String,  _
                    ByVal FatherName As String,  _
                    ByVal FatherIDCode As String,  _
                    ByVal FatherAddress As String,  _
                    ByVal FatherCity As String,  _
                    ByVal MotherMRNo As String,  _
                    ByVal MotherName As String,  _
                    ByVal MotherIDCode As String,  _
                    ByVal MotherAddress As String,  _
                    ByVal HouseNo As String,  _
                    ByVal RT As String,  _
                    ByVal RW As String,  _
                    ByVal DebitorExpired As Date,  _
                    ByVal Education As String,  _
                    ByVal CityCode As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfacePatientMaster/PatGuarantorInsert", ReplyAction:="http://tempuri.org/InterfacePatientMaster/PatGuarantorInsertResponse")>  _
        Function PatGuarantorInsert( _
                    ByVal PatientMRNo As String,  _
                    ByVal GuarantorMRNo As String,  _
                    ByVal GuarantorName As String,  _
                    ByVal GuarantorIDCode As String,  _
                    ByVal GuarantorGender As Char,  _
                    ByVal GuarantorAddress As String,  _
                    ByVal GuarantorCity As String,  _
                    ByVal GuarantorPhone As String,  _
                    ByVal GuarantorOfficeName As String,  _
                    ByVal GuarantorOffAddress As String,  _
                    ByVal GuarantorMobile As String,  _
                    ByVal GuarantorEmpCode As String,  _
                    ByVal GuarantorEmpPosition As String,  _
                    ByVal GuarantorDepartment As String,  _
                    ByVal GuarantorRelation As String,  _
                    ByVal GuarantorOffTel As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfacePatientMaster/PatOtherInsert", ReplyAction:="http://tempuri.org/InterfacePatientMaster/PatOtherInsertResponse")>  _
        Function PatOtherInsert(ByVal PatientMRNo As String, ByVal IntPtr As String, ByVal Language As String, ByVal DoctCode As String, ByVal CorpClient As String, ByVal FinClass As String, ByVal DebitorCode As String, ByVal DebitorRefCode As String, ByVal CreditCardNo As String, ByVal CreditCardExp As Date) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfacePatientMaster/PatContactInsert", ReplyAction:="http://tempuri.org/InterfacePatientMaster/PatContactInsertResponse")>  _
        Function PatContactInsert(ByVal PatientMRNo As String, ByVal ContactMRNo As String, ByVal ConTactName As String, ByVal ContactIDCode As String, ByVal ContactGender As String, ByVal ContactAddress As String, ByVal ContactCity As String, ByVal ContactPhone As String, ByVal ContactRelation As String, ByVal ContactLang As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfacePatientMaster/PatParentInsert", ReplyAction:="http://tempuri.org/InterfacePatientMaster/PatParentInsertResponse")>  _
        Function PatParentInsert(ByVal PatientMRNo As String, ByVal FatherMRNo As String, ByVal FatherName As String, ByVal FatherIDCode As String, ByVal FatherAddress As String, ByVal FatherCity As String, ByVal MotherMRNo As String, ByVal MotherName As String, ByVal MotherIDCode As String, ByVal MotherAddress As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfacePatientMaster/PatUserDefinedInsert", ReplyAction:="http://tempuri.org/InterfacePatientMaster/PatUserDefinedInsertResponse")>  _
        Function PatUserDefinedInsert(ByVal PatientMRNo As String, ByVal HouseNo As String, ByVal RT As String, ByVal RW As String, ByVal DebitorExpired As Date, ByVal Education As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfacePatientMaster/PatientMasterDescAll", ReplyAction:="http://tempuri.org/InterfacePatientMaster/PatientMasterDescAllResponse")>  _
        Function PatientMasterDescAll(ByVal PatientMRNo As String, ByRef ErrorDesc As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfacePatientMaster/PatientUpdate", ReplyAction:="http://tempuri.org/InterfacePatientMaster/PatientUpdateResponse")>  _
        Function PatientUpdate( _
                    ByVal MRNO As String,  _
                    ByVal ReasonUpdate As String,  _
                    ByVal UserUpdate As String,  _
                    ByVal PatName As String,  _
                    ByVal AliasName As String,  _
                    ByVal Gender As Char,  _
                    ByVal IDType As String,  _
                    ByVal IDCode As String,  _
                    ByVal Addr1 As String,  _
                    ByVal Addr2 As String,  _
                    ByVal City As String,  _
                    ByVal State As String,  _
                    ByVal ZipCode As String,  _
                    ByVal Phone As String,  _
                    ByVal Mobile As String,  _
                    ByVal Fax As String,  _
                    ByVal DOB As Date,  _
                    ByVal Nationality As String,  _
                    ByVal Religion As String,  _
                    ByVal ethnicity As String,  _
                    ByVal BirthCountry As String,  _
                    ByVal Place As String,  _
                    ByVal BirthCertificate As String,  _
                    ByVal YearsofRes As Integer,  _
                    ByVal MarStatus As String,  _
                    ByVal Spouse As String,  _
                    ByVal Child As Integer,  _
                    ByVal TotChild As Integer,  _
                    ByVal Occupation As String,  _
                    ByVal Employed As String,  _
                    ByVal RegDate As Date,  _
                    ByVal Visits As Integer,  _
                    ByVal GuarantorMRNo As String,  _
                    ByVal GuarantorName As String,  _
                    ByVal GuarantorIDCode As String,  _
                    ByVal GuarantorGender As Char,  _
                    ByVal GuarantorAddress As String,  _
                    ByVal GuarantorCity As String,  _
                    ByVal GuarantorPhone As String,  _
                    ByVal GuarantorOfficeName As String,  _
                    ByVal GuarantorOffAddress As String,  _
                    ByVal GuarantorMobile As String,  _
                    ByVal GuarantorEmpCode As String,  _
                    ByVal GuarantorEmpPosition As String,  _
                    ByVal GuarantorDepartment As String,  _
                    ByVal GuarantorRelation As String,  _
                    ByVal GuarantorOffTel As String,  _
                    ByVal IntPtr As String,  _
                    ByVal OtherLanguage As String,  _
                    ByVal DoctCode As String,  _
                    ByVal SvcClass As String,  _
                    ByVal FinancialClass As String,  _
                    ByVal DebitorCode As String,  _
                    ByVal DebitorRefCode As String,  _
                    ByVal CreditCardNo As String,  _
                    ByVal CreditCardExp As Date,  _
                    ByVal ContactMRNo As String,  _
                    ByVal ConTactName As String,  _
                    ByVal ContactIDCode As String,  _
                    ByVal ContactGender As String,  _
                    ByVal ContactAddress As String,  _
                    ByVal ContactCity As String,  _
                    ByVal ContactPhone As String,  _
                    ByVal ContactRelation As String,  _
                    ByVal ContactLang As String,  _
                    ByVal FatherMRNo As String,  _
                    ByVal FatherName As String,  _
                    ByVal FatherIDCode As String,  _
                    ByVal FatherAddress As String,  _
                    ByVal FatherCity As String,  _
                    ByVal MotherMRNo As String,  _
                    ByVal MotherName As String,  _
                    ByVal MotherIDCode As String,  _
                    ByVal MotherAddress As String,  _
                    ByVal HouseNo As String,  _
                    ByVal RT As String,  _
                    ByVal RW As String,  _
                    ByVal DebitorExpired As Date,  _
                    ByVal Education As String,  _
                    ByVal CityCode As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfacePatientMaster/Testing", ReplyAction:="http://tempuri.org/InterfacePatientMaster/TestingResponse")>  _
        Function Testing() As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface InterfacePatientMasterChannel
        Inherits SirusPatientMaster.InterfacePatientMaster, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InterfacePatientMasterClient
        Inherits System.ServiceModel.ClientBase(Of SirusPatientMaster.InterfacePatientMaster)
        Implements SirusPatientMaster.InterfacePatientMaster
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function PatientInsert( _
                    ByVal PatName As String,  _
                    ByVal AliasName As String,  _
                    ByVal Gender As Char,  _
                    ByVal IDType As String,  _
                    ByVal IDCode As String,  _
                    ByVal Addr1 As String,  _
                    ByVal Addr2 As String,  _
                    ByVal City As String,  _
                    ByVal State As String,  _
                    ByVal byvalZipCode As String,  _
                    ByVal Phone As String,  _
                    ByVal Mobile As String,  _
                    ByVal Fax As String,  _
                    ByVal DOB As Date,  _
                    ByVal Nationality As String,  _
                    ByVal Religion As String,  _
                    ByVal ethnicity As String,  _
                    ByVal BirthCountry As String,  _
                    ByVal Place As String,  _
                    ByVal BirthCertificate As String,  _
                    ByVal YearsofRes As Integer,  _
                    ByVal MarStatus As String,  _
                    ByVal Spouse As String,  _
                    ByVal Child As Integer,  _
                    ByVal TotChild As Integer,  _
                    ByVal Occupation As String,  _
                    ByVal Employed As String,  _
                    ByVal RegDate As Date,  _
                    ByVal Visits As Integer,  _
                    ByVal GuarantorMRNo As String,  _
                    ByVal GuarantorName As String,  _
                    ByVal GuarantorIDCode As String,  _
                    ByVal GuarantorGender As Char,  _
                    ByVal GuarantorAddress As String,  _
                    ByVal GuarantorCity As String,  _
                    ByVal GuarantorPhone As String,  _
                    ByVal GuarantorOfficeName As String,  _
                    ByVal GuarantorOffAddress As String,  _
                    ByVal GuarantorMobile As String,  _
                    ByVal GuarantorEmpCode As String,  _
                    ByVal GuarantorEmpPosition As String,  _
                    ByVal GuarantorDepartment As String,  _
                    ByVal GuarantorRelation As String,  _
                    ByVal GuarantorOffTel As String,  _
                    ByVal IntPtr As String,  _
                    ByVal Language As String,  _
                    ByVal DoctCode As String,  _
                    ByVal CorpClient As String,  _
                    ByVal FinClass As String,  _
                    ByVal DebitorCode As String,  _
                    ByVal DebitorRefCode As String,  _
                    ByVal CreditCardNo As String,  _
                    ByVal CreditCardExp As Date,  _
                    ByVal ContactMRNo As String,  _
                    ByVal ConTactName As String,  _
                    ByVal ContactIDCode As String,  _
                    ByVal ContactGender As String,  _
                    ByVal ContactAddress As String,  _
                    ByVal ContactCity As String,  _
                    ByVal ContactPhone As String,  _
                    ByVal ContactRelation As String,  _
                    ByVal ContactLang As String,  _
                    ByVal FatherMRNo As String,  _
                    ByVal FatherName As String,  _
                    ByVal FatherIDCode As String,  _
                    ByVal FatherAddress As String,  _
                    ByVal FatherCity As String,  _
                    ByVal MotherMRNo As String,  _
                    ByVal MotherName As String,  _
                    ByVal MotherIDCode As String,  _
                    ByVal MotherAddress As String,  _
                    ByVal HouseNo As String,  _
                    ByVal RT As String,  _
                    ByVal RW As String,  _
                    ByVal DebitorExpired As Date,  _
                    ByVal Education As String,  _
                    ByVal CityCode As String) As String Implements SirusPatientMaster.InterfacePatientMaster.PatientInsert
            Return MyBase.Channel.PatientInsert(PatName, AliasName, Gender, IDType, IDCode, Addr1, Addr2, City, State, byvalZipCode, Phone, Mobile, Fax, DOB, Nationality, Religion, ethnicity, BirthCountry, Place, BirthCertificate, YearsofRes, MarStatus, Spouse, Child, TotChild, Occupation, Employed, RegDate, Visits, GuarantorMRNo, GuarantorName, GuarantorIDCode, GuarantorGender, GuarantorAddress, GuarantorCity, GuarantorPhone, GuarantorOfficeName, GuarantorOffAddress, GuarantorMobile, GuarantorEmpCode, GuarantorEmpPosition, GuarantorDepartment, GuarantorRelation, GuarantorOffTel, IntPtr, Language, DoctCode, CorpClient, FinClass, DebitorCode, DebitorRefCode, CreditCardNo, CreditCardExp, ContactMRNo, ConTactName, ContactIDCode, ContactGender, ContactAddress, ContactCity, ContactPhone, ContactRelation, ContactLang, FatherMRNo, FatherName, FatherIDCode, FatherAddress, FatherCity, MotherMRNo, MotherName, MotherIDCode, MotherAddress, HouseNo, RT, RW, DebitorExpired, Education, CityCode)
        End Function
        
        Public Function PatGuarantorInsert( _
                    ByVal PatientMRNo As String,  _
                    ByVal GuarantorMRNo As String,  _
                    ByVal GuarantorName As String,  _
                    ByVal GuarantorIDCode As String,  _
                    ByVal GuarantorGender As Char,  _
                    ByVal GuarantorAddress As String,  _
                    ByVal GuarantorCity As String,  _
                    ByVal GuarantorPhone As String,  _
                    ByVal GuarantorOfficeName As String,  _
                    ByVal GuarantorOffAddress As String,  _
                    ByVal GuarantorMobile As String,  _
                    ByVal GuarantorEmpCode As String,  _
                    ByVal GuarantorEmpPosition As String,  _
                    ByVal GuarantorDepartment As String,  _
                    ByVal GuarantorRelation As String,  _
                    ByVal GuarantorOffTel As String) As Long Implements SirusPatientMaster.InterfacePatientMaster.PatGuarantorInsert
            Return MyBase.Channel.PatGuarantorInsert(PatientMRNo, GuarantorMRNo, GuarantorName, GuarantorIDCode, GuarantorGender, GuarantorAddress, GuarantorCity, GuarantorPhone, GuarantorOfficeName, GuarantorOffAddress, GuarantorMobile, GuarantorEmpCode, GuarantorEmpPosition, GuarantorDepartment, GuarantorRelation, GuarantorOffTel)
        End Function
        
        Public Function PatOtherInsert(ByVal PatientMRNo As String, ByVal IntPtr As String, ByVal Language As String, ByVal DoctCode As String, ByVal CorpClient As String, ByVal FinClass As String, ByVal DebitorCode As String, ByVal DebitorRefCode As String, ByVal CreditCardNo As String, ByVal CreditCardExp As Date) As String Implements SirusPatientMaster.InterfacePatientMaster.PatOtherInsert
            Return MyBase.Channel.PatOtherInsert(PatientMRNo, IntPtr, Language, DoctCode, CorpClient, FinClass, DebitorCode, DebitorRefCode, CreditCardNo, CreditCardExp)
        End Function
        
        Public Function PatContactInsert(ByVal PatientMRNo As String, ByVal ContactMRNo As String, ByVal ConTactName As String, ByVal ContactIDCode As String, ByVal ContactGender As String, ByVal ContactAddress As String, ByVal ContactCity As String, ByVal ContactPhone As String, ByVal ContactRelation As String, ByVal ContactLang As String) As String Implements SirusPatientMaster.InterfacePatientMaster.PatContactInsert
            Return MyBase.Channel.PatContactInsert(PatientMRNo, ContactMRNo, ConTactName, ContactIDCode, ContactGender, ContactAddress, ContactCity, ContactPhone, ContactRelation, ContactLang)
        End Function
        
        Public Function PatParentInsert(ByVal PatientMRNo As String, ByVal FatherMRNo As String, ByVal FatherName As String, ByVal FatherIDCode As String, ByVal FatherAddress As String, ByVal FatherCity As String, ByVal MotherMRNo As String, ByVal MotherName As String, ByVal MotherIDCode As String, ByVal MotherAddress As String) As String Implements SirusPatientMaster.InterfacePatientMaster.PatParentInsert
            Return MyBase.Channel.PatParentInsert(PatientMRNo, FatherMRNo, FatherName, FatherIDCode, FatherAddress, FatherCity, MotherMRNo, MotherName, MotherIDCode, MotherAddress)
        End Function
        
        Public Function PatUserDefinedInsert(ByVal PatientMRNo As String, ByVal HouseNo As String, ByVal RT As String, ByVal RW As String, ByVal DebitorExpired As Date, ByVal Education As String) As String Implements SirusPatientMaster.InterfacePatientMaster.PatUserDefinedInsert
            Return MyBase.Channel.PatUserDefinedInsert(PatientMRNo, HouseNo, RT, RW, DebitorExpired, Education)
        End Function
        
        Public Function PatientMasterDescAll(ByVal PatientMRNo As String, ByRef ErrorDesc As String) As System.Data.DataTable Implements SirusPatientMaster.InterfacePatientMaster.PatientMasterDescAll
            Return MyBase.Channel.PatientMasterDescAll(PatientMRNo, ErrorDesc)
        End Function
        
        Public Function PatientUpdate( _
                    ByVal MRNO As String,  _
                    ByVal ReasonUpdate As String,  _
                    ByVal UserUpdate As String,  _
                    ByVal PatName As String,  _
                    ByVal AliasName As String,  _
                    ByVal Gender As Char,  _
                    ByVal IDType As String,  _
                    ByVal IDCode As String,  _
                    ByVal Addr1 As String,  _
                    ByVal Addr2 As String,  _
                    ByVal City As String,  _
                    ByVal State As String,  _
                    ByVal ZipCode As String,  _
                    ByVal Phone As String,  _
                    ByVal Mobile As String,  _
                    ByVal Fax As String,  _
                    ByVal DOB As Date,  _
                    ByVal Nationality As String,  _
                    ByVal Religion As String,  _
                    ByVal ethnicity As String,  _
                    ByVal BirthCountry As String,  _
                    ByVal Place As String,  _
                    ByVal BirthCertificate As String,  _
                    ByVal YearsofRes As Integer,  _
                    ByVal MarStatus As String,  _
                    ByVal Spouse As String,  _
                    ByVal Child As Integer,  _
                    ByVal TotChild As Integer,  _
                    ByVal Occupation As String,  _
                    ByVal Employed As String,  _
                    ByVal RegDate As Date,  _
                    ByVal Visits As Integer,  _
                    ByVal GuarantorMRNo As String,  _
                    ByVal GuarantorName As String,  _
                    ByVal GuarantorIDCode As String,  _
                    ByVal GuarantorGender As Char,  _
                    ByVal GuarantorAddress As String,  _
                    ByVal GuarantorCity As String,  _
                    ByVal GuarantorPhone As String,  _
                    ByVal GuarantorOfficeName As String,  _
                    ByVal GuarantorOffAddress As String,  _
                    ByVal GuarantorMobile As String,  _
                    ByVal GuarantorEmpCode As String,  _
                    ByVal GuarantorEmpPosition As String,  _
                    ByVal GuarantorDepartment As String,  _
                    ByVal GuarantorRelation As String,  _
                    ByVal GuarantorOffTel As String,  _
                    ByVal IntPtr As String,  _
                    ByVal OtherLanguage As String,  _
                    ByVal DoctCode As String,  _
                    ByVal SvcClass As String,  _
                    ByVal FinancialClass As String,  _
                    ByVal DebitorCode As String,  _
                    ByVal DebitorRefCode As String,  _
                    ByVal CreditCardNo As String,  _
                    ByVal CreditCardExp As Date,  _
                    ByVal ContactMRNo As String,  _
                    ByVal ConTactName As String,  _
                    ByVal ContactIDCode As String,  _
                    ByVal ContactGender As String,  _
                    ByVal ContactAddress As String,  _
                    ByVal ContactCity As String,  _
                    ByVal ContactPhone As String,  _
                    ByVal ContactRelation As String,  _
                    ByVal ContactLang As String,  _
                    ByVal FatherMRNo As String,  _
                    ByVal FatherName As String,  _
                    ByVal FatherIDCode As String,  _
                    ByVal FatherAddress As String,  _
                    ByVal FatherCity As String,  _
                    ByVal MotherMRNo As String,  _
                    ByVal MotherName As String,  _
                    ByVal MotherIDCode As String,  _
                    ByVal MotherAddress As String,  _
                    ByVal HouseNo As String,  _
                    ByVal RT As String,  _
                    ByVal RW As String,  _
                    ByVal DebitorExpired As Date,  _
                    ByVal Education As String,  _
                    ByVal CityCode As String) As String Implements SirusPatientMaster.InterfacePatientMaster.PatientUpdate
            Return MyBase.Channel.PatientUpdate(MRNO, ReasonUpdate, UserUpdate, PatName, AliasName, Gender, IDType, IDCode, Addr1, Addr2, City, State, ZipCode, Phone, Mobile, Fax, DOB, Nationality, Religion, ethnicity, BirthCountry, Place, BirthCertificate, YearsofRes, MarStatus, Spouse, Child, TotChild, Occupation, Employed, RegDate, Visits, GuarantorMRNo, GuarantorName, GuarantorIDCode, GuarantorGender, GuarantorAddress, GuarantorCity, GuarantorPhone, GuarantorOfficeName, GuarantorOffAddress, GuarantorMobile, GuarantorEmpCode, GuarantorEmpPosition, GuarantorDepartment, GuarantorRelation, GuarantorOffTel, IntPtr, OtherLanguage, DoctCode, SvcClass, FinancialClass, DebitorCode, DebitorRefCode, CreditCardNo, CreditCardExp, ContactMRNo, ConTactName, ContactIDCode, ContactGender, ContactAddress, ContactCity, ContactPhone, ContactRelation, ContactLang, FatherMRNo, FatherName, FatherIDCode, FatherAddress, FatherCity, MotherMRNo, MotherName, MotherIDCode, MotherAddress, HouseNo, RT, RW, DebitorExpired, Education, CityCode)
        End Function
        
        Public Function Testing() As String Implements SirusPatientMaster.InterfacePatientMaster.Testing
            Return MyBase.Channel.Testing
        End Function
    End Class
End Namespace
