'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SirusLookUp
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SirusLookUp.InterFaceLookUp")>  _
    Public Interface InterFaceLookUp
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpCityKab", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpCityKabResponse")>  _
        Function LookUpCityKab() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpKabupatenProv", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpKabupatenProvResponse")>  _
        Function LookUpKabupatenProv() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpProvinsi", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpProvinsiResponse")>  _
        Function LookUpProvinsi() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpAgama", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpAgamaResponse")>  _
        Function LookUpAgama() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpEtnik", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpEtnikResponse")>  _
        Function LookUpEtnik() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpMaritalSMS", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpMaritalSMSResponse")>  _
        Function LookUpMaritalSMS() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpKecKabProv", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpKecKabProvResponse")>  _
        Function LookUpKecKabProv() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpPekerjaan", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpPekerjaanResponse")>  _
        Function LookUpPekerjaan() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpNationality", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpNationalityResponse")>  _
        Function LookUpNationality() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpPendidikan", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpPendidikanResponse")>  _
        Function LookUpPendidikan() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpFinancialClass", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpFinancialClassResponse")>  _
        Function LookUpFinancialClass() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpDoctor", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpDoctorResponse")>  _
        Function LookUpDoctor() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpLanguage", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpLanguageResponse")>  _
        Function LookUpLanguage() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpKabupaten", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpKabupatenResponse")>  _
        Function LookUpKabupaten() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpCity", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpCityResponse")>  _
        Function LookUpCity() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpDebitor", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpDebitorResponse")>  _
        Function LookUpDebitor() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpSvcClass", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpSvcClassResponse")>  _
        Function LookUpSvcClass() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/LookUpPatient", ReplyAction:="http://tempuri.org/InterFaceLookUp/LookUpPatientResponse")>  _
        Function LookUpPatient(ByVal PatientName As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/GetWilayah", ReplyAction:="http://tempuri.org/InterFaceLookUp/GetWilayahResponse")>  _
        Function GetWilayah(ByVal CityCode As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterFaceLookUp/PatientMasterFolio", ReplyAction:="http://tempuri.org/InterFaceLookUp/PatientMasterFolioResponse")>  _
        Function PatientMasterFolio(ByVal MRNo As String, ByVal PatientName As String) As System.Data.DataTable
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface InterFaceLookUpChannel
        Inherits SirusLookUp.InterFaceLookUp, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InterFaceLookUpClient
        Inherits System.ServiceModel.ClientBase(Of SirusLookUp.InterFaceLookUp)
        Implements SirusLookUp.InterFaceLookUp
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function LookUpCityKab() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpCityKab
            Return MyBase.Channel.LookUpCityKab
        End Function
        
        Public Function LookUpKabupatenProv() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpKabupatenProv
            Return MyBase.Channel.LookUpKabupatenProv
        End Function
        
        Public Function LookUpProvinsi() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpProvinsi
            Return MyBase.Channel.LookUpProvinsi
        End Function
        
        Public Function LookUpAgama() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpAgama
            Return MyBase.Channel.LookUpAgama
        End Function
        
        Public Function LookUpEtnik() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpEtnik
            Return MyBase.Channel.LookUpEtnik
        End Function
        
        Public Function LookUpMaritalSMS() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpMaritalSMS
            Return MyBase.Channel.LookUpMaritalSMS
        End Function
        
        Public Function LookUpKecKabProv() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpKecKabProv
            Return MyBase.Channel.LookUpKecKabProv
        End Function
        
        Public Function LookUpPekerjaan() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpPekerjaan
            Return MyBase.Channel.LookUpPekerjaan
        End Function
        
        Public Function LookUpNationality() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpNationality
            Return MyBase.Channel.LookUpNationality
        End Function
        
        Public Function LookUpPendidikan() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpPendidikan
            Return MyBase.Channel.LookUpPendidikan
        End Function
        
        Public Function LookUpFinancialClass() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpFinancialClass
            Return MyBase.Channel.LookUpFinancialClass
        End Function
        
        Public Function LookUpDoctor() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpDoctor
            Return MyBase.Channel.LookUpDoctor
        End Function
        
        Public Function LookUpLanguage() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpLanguage
            Return MyBase.Channel.LookUpLanguage
        End Function
        
        Public Function LookUpKabupaten() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpKabupaten
            Return MyBase.Channel.LookUpKabupaten
        End Function
        
        Public Function LookUpCity() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpCity
            Return MyBase.Channel.LookUpCity
        End Function
        
        Public Function LookUpDebitor() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpDebitor
            Return MyBase.Channel.LookUpDebitor
        End Function
        
        Public Function LookUpSvcClass() As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpSvcClass
            Return MyBase.Channel.LookUpSvcClass
        End Function
        
        Public Function LookUpPatient(ByVal PatientName As String) As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.LookUpPatient
            Return MyBase.Channel.LookUpPatient(PatientName)
        End Function
        
        Public Function GetWilayah(ByVal CityCode As String) As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.GetWilayah
            Return MyBase.Channel.GetWilayah(CityCode)
        End Function
        
        Public Function PatientMasterFolio(ByVal MRNo As String, ByVal PatientName As String) As System.Data.DataTable Implements SirusLookUp.InterFaceLookUp.PatientMasterFolio
            Return MyBase.Channel.PatientMasterFolio(MRNo, PatientName)
        End Function
    End Class
End Namespace
