'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SirusAdmisiGrd
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SirusAdmisiGrd.InterfaceAdmission")>  _
    Public Interface InterfaceAdmission
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfaceAdmission/FolioAdd", ReplyAction:="http://tempuri.org/InterfaceAdmission/FolioAddResponse")>  _
        Function FolioAdd( _
                    ByVal MRNo As String,  _
                    ByVal PatType As String,  _
                    ByVal AdmDate As Date,  _
                    ByVal DoctCode As String,  _
                    ByVal Operators As String,  _
                    ByVal PolyCode As String,  _
                    ByVal AdmSource As String,  _
                    ByVal GuaNo As Long,  _
                    ByVal DbtCode As String,  _
                    ByVal RefferedBy As String,  _
                    ByVal TransferFrom As String,  _
                    ByVal Reference As String,  _
                    ByVal BedNo As String,  _
                    ByVal DischNo As String,  _
                    ByVal Deposit As Single,  _
                    ByVal Balance As Single,  _
                    ByVal SvcClass As String,  _
                    ByVal visitno As Integer,  _
                    ByVal Diagnosis As String,  _
                    ByVal DiagnDesc As String,  _
                    ByVal OrgClass As String,  _
                    ByVal HighClass As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfaceAdmission/FolioUpdate", ReplyAction:="http://tempuri.org/InterfaceAdmission/FolioUpdateResponse")>  _
        Function FolioUpdate( _
                    ByVal FolioNo As String,  _
                    ByVal MRNo As String,  _
                    ByVal PatType As String,  _
                    ByVal AdmDate As Date,  _
                    ByVal DoctCode As String,  _
                    ByVal Operators As String,  _
                    ByVal PolyCode As String,  _
                    ByVal AdmSource As String,  _
                    ByVal GuaNo As Long,  _
                    ByVal DbtCode As String,  _
                    ByVal RefferedBy As String,  _
                    ByVal TransferFrom As String,  _
                    ByVal Reference As String,  _
                    ByVal BedNo As String,  _
                    ByVal DischNo As String,  _
                    ByVal Deposit As Single,  _
                    ByVal Balance As Single,  _
                    ByVal SvcClass As String,  _
                    ByVal visitno As Integer,  _
                    ByVal Diagnosis As String,  _
                    ByVal DiagnDesc As String,  _
                    ByVal OrgClass As String,  _
                    ByVal HighClass As String) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfaceAdmission/FolioDetailSelect", ReplyAction:="http://tempuri.org/InterfaceAdmission/FolioDetailSelectResponse")>  _
        Function FolioDetailSelect(ByVal FolioNo As String, ByRef ErrorDesc As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfaceAdmission/FolioUpdateDeposit", ReplyAction:="http://tempuri.org/InterfaceAdmission/FolioUpdateDepositResponse")>  _
        Function FolioUpdateDeposit(ByVal FolioNo As String, ByVal Deposit As Double, ByVal Balance As Double) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InterfaceAdmission/LoadBillObat", ReplyAction:="http://tempuri.org/InterfaceAdmission/LoadBillObatResponse")>  _
        Function LoadBillObat(ByVal foliono As String, ByVal SvcClass As String, ByVal DebitorID As String, ByRef Message As String) As System.Data.DataTable
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface InterfaceAdmissionChannel
        Inherits SirusAdmisiGrd.InterfaceAdmission, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InterfaceAdmissionClient
        Inherits System.ServiceModel.ClientBase(Of SirusAdmisiGrd.InterfaceAdmission)
        Implements SirusAdmisiGrd.InterfaceAdmission
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function FolioAdd( _
                    ByVal MRNo As String,  _
                    ByVal PatType As String,  _
                    ByVal AdmDate As Date,  _
                    ByVal DoctCode As String,  _
                    ByVal Operators As String,  _
                    ByVal PolyCode As String,  _
                    ByVal AdmSource As String,  _
                    ByVal GuaNo As Long,  _
                    ByVal DbtCode As String,  _
                    ByVal RefferedBy As String,  _
                    ByVal TransferFrom As String,  _
                    ByVal Reference As String,  _
                    ByVal BedNo As String,  _
                    ByVal DischNo As String,  _
                    ByVal Deposit As Single,  _
                    ByVal Balance As Single,  _
                    ByVal SvcClass As String,  _
                    ByVal visitno As Integer,  _
                    ByVal Diagnosis As String,  _
                    ByVal DiagnDesc As String,  _
                    ByVal OrgClass As String,  _
                    ByVal HighClass As String) As Object Implements SirusAdmisiGrd.InterfaceAdmission.FolioAdd
            Return MyBase.Channel.FolioAdd(MRNo, PatType, AdmDate, DoctCode, Operators, PolyCode, AdmSource, GuaNo, DbtCode, RefferedBy, TransferFrom, Reference, BedNo, DischNo, Deposit, Balance, SvcClass, visitno, Diagnosis, DiagnDesc, OrgClass, HighClass)
        End Function
        
        Public Function FolioUpdate( _
                    ByVal FolioNo As String,  _
                    ByVal MRNo As String,  _
                    ByVal PatType As String,  _
                    ByVal AdmDate As Date,  _
                    ByVal DoctCode As String,  _
                    ByVal Operators As String,  _
                    ByVal PolyCode As String,  _
                    ByVal AdmSource As String,  _
                    ByVal GuaNo As Long,  _
                    ByVal DbtCode As String,  _
                    ByVal RefferedBy As String,  _
                    ByVal TransferFrom As String,  _
                    ByVal Reference As String,  _
                    ByVal BedNo As String,  _
                    ByVal DischNo As String,  _
                    ByVal Deposit As Single,  _
                    ByVal Balance As Single,  _
                    ByVal SvcClass As String,  _
                    ByVal visitno As Integer,  _
                    ByVal Diagnosis As String,  _
                    ByVal DiagnDesc As String,  _
                    ByVal OrgClass As String,  _
                    ByVal HighClass As String) As Object Implements SirusAdmisiGrd.InterfaceAdmission.FolioUpdate
            Return MyBase.Channel.FolioUpdate(FolioNo, MRNo, PatType, AdmDate, DoctCode, Operators, PolyCode, AdmSource, GuaNo, DbtCode, RefferedBy, TransferFrom, Reference, BedNo, DischNo, Deposit, Balance, SvcClass, visitno, Diagnosis, DiagnDesc, OrgClass, HighClass)
        End Function
        
        Public Function FolioDetailSelect(ByVal FolioNo As String, ByRef ErrorDesc As String) As System.Data.DataTable Implements SirusAdmisiGrd.InterfaceAdmission.FolioDetailSelect
            Return MyBase.Channel.FolioDetailSelect(FolioNo, ErrorDesc)
        End Function
        
        Public Function FolioUpdateDeposit(ByVal FolioNo As String, ByVal Deposit As Double, ByVal Balance As Double) As String Implements SirusAdmisiGrd.InterfaceAdmission.FolioUpdateDeposit
            Return MyBase.Channel.FolioUpdateDeposit(FolioNo, Deposit, Balance)
        End Function
        
        Public Function LoadBillObat(ByVal foliono As String, ByVal SvcClass As String, ByVal DebitorID As String, ByRef Message As String) As System.Data.DataTable Implements SirusAdmisiGrd.InterfaceAdmission.LoadBillObat
            Return MyBase.Channel.LoadBillObat(foliono, SvcClass, DebitorID, Message)
        End Function
    End Class
End Namespace
